# Generated by Django 4.2.7 on 2026-05-18 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaint', models.TextField()),
                ('history_of_illness', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='opd.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='opd.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveIntegerField(help_text='mmHg')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(help_text='mmHg')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='°C', max_digits=4)),
                ('heart_rate', models.PositiveIntegerField(help_text='bpm')),
                ('respiratory_rate', models.PositiveIntegerField(help_text='breaths/min')),
                ('oxygen_saturation', models.PositiveIntegerField(help_text='SpO2 %')),
                ('weight', models.DecimalField(decimal_places=1, help_text='kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, help_text='cm', max_digits=5)),
                ('pain_scale', models.PositiveIntegerField(default=0, help_text='0-10')),
                ('chief_complaint', models.TextField()),
                ('nurse_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='opd.appointment')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='opd.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.consultation')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='opd.patient')),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('result', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='clinical.consultation')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='opd.patient')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
    ]
