# Generated by Django 6.0.6 on 2026-06-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0007_alter_appointment_options_alter_appointment_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_range', models.TextField(help_text='Reference limits (e.g., Male: 13.5-17.5 g/dL)')),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ordered', 'Awaiting Sample'), ('processing', 'Processing'), ('completed', 'Results Released')], default='ordered', max_length=20)),
                ('result_values', models.TextField(blank=True, help_text='Observed patient values')),
                ('lab_notes', models.TextField(blank=True, help_text='Pathologist comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialized_lab_appointments', to='opd.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialized_lab_orders', to='opd.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.labtestcatalog')),
            ],
        ),
    ]
