# Generated by Django 6.0.6 on 2026-06-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0007_alter_appointment_options_alter_appointment_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalProcedureCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DentalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(blank=True, help_text='Tooth identity notation system (e.g. 14, 32)', max_length=50)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialized_dental_appointments', to='opd.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialized_dental_encounters', to='opd.patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dental.dentalprocedurecatalog')),
            ],
        ),
    ]
