# Generated by Django 4.2.7 on 2026-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('doctor', 'General Practitioner'), ('surgeon', 'General Surgeon'), ('physician', 'Physician / Internist'), ('pediatrician', 'Pediatrician'), ('gynecologist', 'Gynecologist / Obstetrician'), ('cardiologist', 'Cardiologist'), ('neurologist', 'Neurologist'), ('neurosurgeon', 'Neurosurgeon'), ('orthopedic', 'Orthopedic Surgeon'), ('dermatologist', 'Dermatologist'), ('psychiatrist', 'Psychiatrist'), ('radiologist', 'Radiologist'), ('anesthesiologist', 'Anesthesiologist'), ('urologist', 'Urologist'), ('oncologist', 'Oncologist'), ('ent', 'ENT Specialist'), ('ophthalmologist', 'Ophthalmologist (Eye)'), ('dentist', 'Dentist'), ('physiotherapist', 'Physiotherapist'), ('lab_technician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('nutritionist', 'Nutritionist / Dietitian')], default='receptionist', max_length=20),
        ),
    ]
