# Generated by Django 6.0.6 on 2026-06-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0007_alter_appointment_options_alter_appointment_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OpticalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_sphere', models.CharField(blank=True, max_length=10, verbose_name='OD Sphere')),
                ('od_cylinder', models.CharField(blank=True, max_length=10, verbose_name='OD Cylinder')),
                ('od_axis', models.CharField(blank=True, max_length=10, verbose_name='OD Axis')),
                ('os_sphere', models.CharField(blank=True, max_length=10, verbose_name='OS Sphere')),
                ('os_cylinder', models.CharField(blank=True, max_length=10, verbose_name='OS Cylinder')),
                ('os_axis', models.CharField(blank=True, max_length=10, verbose_name='OS Axis')),
                ('pd', models.CharField(blank=True, max_length=10, verbose_name='Pupillary Distance')),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialized_optical_appointments', to='opd.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialized_optical_prescriptions', to='opd.patient')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='optical.opticalservicecatalog')),
            ],
        ),
    ]
