# Generated by Django 4.2.7 on 2026-05-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_remove_appointment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(blank=True, choices=[('treated', 'Treated'), ('discharged', 'Discharged'), ('admitted', 'Admitted'), ('medicine_only', 'Medication only'), ('died', 'Died')], max_length=30),
        ),
    ]
