# Generated by Django 4.2.7 on 2026-05-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_appointment_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='next_step',
            field=models.CharField(blank=True, choices=[('', '—'), ('lab', 'Lab'), ('reception', 'Reception'), ('pharmacy', 'Pharmacy'), ('ward', 'Ward'), ('cashier', 'Cashier'), ('follow_up', 'Follow-up'), ('home', 'Home')], max_length=30),
        ),
    ]
