# Generated by Django 4.2.7 on 2026-05-29 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opd', '0004_appointment_next_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opd.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='next_step',
            field=models.CharField(blank=True, choices=[('', 'Next step'), ('triage', 'Triage'), ('doctor', 'Doctor'), ('lab', 'Lab'), ('reception', 'Reception'), ('pharmacy', 'Pharmacy'), ('ward', 'Ward'), ('cashier', 'Cashier'), ('follow_up', 'Follow-up'), ('home', 'Home')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
