# Generated by Django 4.2.7 on 2026-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_alter_appointment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='next_step',
            field=models.CharField(blank=True, choices=[('', 'Next step'), ('triage', 'Triage'), ('doctor', 'Doctor'), ('lab', 'Lab'), ('reception', 'Reception'), ('pharmacy', 'Pharmacy'), ('ward', 'Ward'), ('cashier', 'Cashier'), ('follow_up', 'Follow-up'), ('home', 'Home'), ('discharged', 'Discharged'), ('admitted', 'Admitted'), ('nutrition', 'Nutrition'), ('physiotherapy', 'Physiotherapy'), ('dental', 'Dental'), ('optical', 'Optical')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(blank=True, choices=[('treated', 'Treated'), ('discharged', 'Discharged'), ('admitted', 'Admitted'), ('medicine_only', 'Medication Only'), ('died', 'Died')], default='', max_length=20),
        ),
    ]
