# Generated by Django 4.2.7 on 2026-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_date', 'scheduled_time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
